export const ACCOUNT_PASSWORD_FORM = 'AUTH/SIGNUP/ACCOUNT_PASSWORD_FORM'
export const COPY_YOUR_ACCOUNT_PASSWORD_FORM = 'AUTH/SIGNUP/COPY_YOUR_ACCOUNT_PASSWORD_FORM'
export const CONFIRM_BACK_UP_FORM = 'AUTH/SIGNUP/CONFIRM_BACK_UP_FORM'
