dist: trusty
os: linux
group: stable
language: node_js
node_js:
  - 8

install:
  - yarn install

cache:
  directories:
    - node_modules

script:
  - yarn run lint
  - yarn run test:coverage

#after_script:
#    - cat ./coverage/lcov.info | ./node_modules/./bin/coveralls

after_success: ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls