dist: trusty
os: linux
group: stable
language: node_js
node_js:
  - 6

install:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm test -- --coverage
  #- npm run build

after_script:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
