language: node_js

node_js:
  - "stable"

sudo: false

before_script:
  - yarn global add @rispa/cli@latest
  - ris all compile

script:
  - ris all lint
  - ris all stylelint
  - ris all test:coverage

# notifications:
#   slack:
#     rooms:
#
#     on_success: always
#     on_failure: always
#     on_start: never
#   webhooks:
#     urls:
#
#     on_success: always
#     on_failure: never
#     on_start: never

cache:
  yarn: true
