export const ACCOUNT_PASSWORD_FORM = 'SIGNUP/ACCOUNT_PASSWORD_FORM'
export const COPY_YOUR_ACCOUNT_PASSWORD_FORM = 'SIGNUP/COPY_YOUR_ACCOUNT_PASSWORD_FORM'
export const CONFIRM_BACK_UP_FORM = 'SIGNUP/CONFIRM_BACK_UP_FORM'